name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  version:
    description: 'GitVersion tool version'
    default: 'latest'
  installOnly:
    description: 'Only install GitVersion tool'
    default: false
runs:
  using: 'node12'
  main: 'lib/bundle.js'
