name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  version:
    description: 'GitVersion tool version'
    default: 'latest'
runs:
  using: 'node12'
  main: 'lib/bundle.js'
