name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  milliseconds:
    description: 'The number of milliseconds to wait'
    default: 1000
runs:
  using: 'node12'
  main: 'lib/main.js'
